# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'craveThru' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for craveThru
  pod "Parse"
  pod "AlamofireImage"
  pod "Firebase/Core"
  pod "Firebase/Database"
  pod "Firebase/Auth"
  pod "Firebase/Firestore"
  pod "iCarousel", "~> 1.8"

  target 'craveThruTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'craveThruUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
